#
# Module manifest for module 'AzureStack'
#
# Generated by: Microsoft Corporation
#
# Generated on: 02/26/2018 14:10:39
#

$PSDefaultParameterValues.Clear()
Set-StrictMode -Version Latest

Import-Module AzureRM.Profile -RequiredVersion 4.2.0
Import-Module Azs.AzureBridge.Admin -RequiredVersion 0.10
Import-Module Azs.Backup.Admin -RequiredVersion 0.10
Import-Module Azs.Commerce.Admin -RequiredVersion 0.10
Import-Module Azs.Compute.Admin -RequiredVersion 0.10
Import-Module Azs.Fabric.Admin -RequiredVersion 0.10
Import-Module Azs.Gallery.Admin -RequiredVersion 0.10
Import-Module Azs.InfrastructureInsights.Admin -RequiredVersion 0.10
Import-Module Azs.KeyVault.Admin -RequiredVersion 0.10
Import-Module Azs.Network.Admin -RequiredVersion 0.10
Import-Module Azs.Storage.Admin -RequiredVersion 0.10
Import-Module Azs.Subscriptions.Admin -RequiredVersion 0.10
Import-Module Azs.Update.Admin -RequiredVersion 0.10


if (Test-Path -Path "$PSScriptRoot\StartupScripts")
{
    Get-ChildItem "$PSScriptRoot\StartupScripts" | ForEach-Object {
        . $_.FullName
    }
}

if ($PSVersionTable.PSVersion.Major -ge 5)
{
    $completerCommands = @()

    $completerCommands | ForEach-Object {
        $type = $_.AttributeType
        $args = "@()"
        if ($_.ArgumentList.Count -ne 0) {
		    $temp = $_.ArgumentList -join "`", `""
            $args = "@(`"" + $temp + "`")"
        }
        $sb = [scriptblock]::Create("param(`$commandName, `$parameterName, `$wordToComplete, `$commandAst, `$fakeBoundParameter) `
        `$completerObject = New-Object $type -ArgumentList $args `
        `$arguments = `$completerObject.GetCompleterValues() `
        `$wordToCompleteTrimQuote = `$wordToComplete.Trim(`"'`")
        `$wordToCompleteTrimmed = `$wordToCompleteTrimQuote.Trim(`"```"`")
        `$arguments | Where-Object { (`$_ -Like `"`$wordToComplete*`")  -or (`$_ -Like `"```'`$wordToCompleteTrimmed*```'`") } | ForEach-Object { [System.Management.Automation.CompletionResult]::new(`$_, `$_, 'ParameterValue', `$_) }")
        Register-ArgumentCompleter -CommandName $_.Command -ParameterName $_.Parameter -ScriptBlock $sb
    }
}
else
{

}

$FilteredCommands = @()

$FilteredCommands | ForEach-Object {
	$global:PSDefaultParameterValues.Add($_,
		{
			$context = Get-AzureRmContext
			if (($context -ne $null) -and $context.ExtendedProperties.ContainsKey("Default Resource Group")) {
				$context.ExtendedProperties["Default Resource Group"]
			}
		})
}
